project:
  type: website
  output-dir: docs

website:
  title: "Ayan Sayani - PSCI 3200"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: "SANCTION V3.html"
        text: Research

format:
  html:
    theme: cosmo
    toc: true