project: 
  type: website
  output-dir: docs

website:
  title: "Ayan Sayani - PSCI 3200"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sanction.qmd
        text: Research