<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Final Presentation Research Design</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="SANCTION V3_files/libs/clipboard/clipboard.min.js"></script>
<script src="SANCTION V3_files/libs/quarto-html/quarto.js"></script>
<script src="SANCTION V3_files/libs/quarto-html/popper.min.js"></script>
<script src="SANCTION V3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SANCTION V3_files/libs/quarto-html/anchor.min.js"></script>
<link href="SANCTION V3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SANCTION V3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SANCTION V3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SANCTION V3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SANCTION V3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Presentation Research Design</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This paper examines whether U.S.-only trade sanctions affect political corruption, and whether these effects vary across regime type. Using a country-year panel of ever-sanctioned countries from 2003–2023, I construct a continuous sanctions-intensity measure combining sanctions status, pre-sanction trade openness, and sanction duration in order to move beyond the binary sanctions indicators commonly used in the literature. Corruption is measured using V-Dem’s Political Corruption Index, while the empirical strategy relies on two-way fixed effects models, interaction terms for democracy, placebo lead tests, and country-specific time trends as robustness checks. Initial results suggest a statistically significant negative relationship between sanctions intensity and corruption in less democratic regimes, contrary to the paper’s original hypothesis. However, these findings weaken substantially once country-specific time trends are introduced, while placebo tests remain significant, raising concerns about pre-existing institutional trajectories and time-varying confounders. Overall, the paper finds limited evidence that more intense U.S.-only trade sanctions systematically increase corruption, and calls for the usage of continuous sanction-intensity measures combined with more viable methods such as difference-in-difference panel tests or event studies to gain a casual vantage point.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">(1) Introduction</h2>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">Research Question</h3>
<p><strong>This project will attempt to explore and answer the question, “Do economic sanctions imposed by the United States from 2003 to 2023 affect the level of corruption in recipient countries?”</strong></p>
<p>This question is increasingly important because sanctions continue to be one of the primary foreign policy tools used by the United States and other major powers, often justified as mechanisms for promoting institutional reform, accountability, or political change. However, if sanctions instead worsen corruption or weaken already fragile institutions, especially in less democratic states, then they may unintentionally reinforce many of the governance problems they are meant to combat.</p>
<p>Existing research generally finds that economic sanctions tend to increase corruption in target countries through the distortion of economic activity and the expansion of opportunities for rent-seeking behavior. For example, Dreher, Gassebner, and Siemers (2017) [<span class="citation" data-cites="dreher2017">Dreher, Gassebner, and Siemers (<a href="#ref-dreher2017" role="doc-biblioref">2017</a>)</span>] find that sanctions are associated with significantly higher levels of corruption, particularly in more autocratic regimes, and through their panel analysis with country and year fixed effects argue that sanctions restrict formal economic channels in ways that increase scarcity and discretionary power among political officials, thus fostering bribery, patronage, and informal exchange. Similarly, Neuenkirch and Neumeier (2016) <span class="citation" data-cites="neuenkirch2016">(<a href="#ref-neuenkirch2016" role="doc-biblioref">Neuenkirch and Neumeier 2016</a>)</span> show that U.S. sanctions lead to substantial declines in economic growth in targeted countries, and while their study focuses more on macroeconomic outcomes than corruption directly, it still provides an important mechanism through which sanctions may weaken institutions and shift economic activity into informal sectors commonly associated with corruption and weaker oversight. Taken together, the existing literature broadly points toward the idea that sanctions may unintentionally worsen corruption by weakening formal markets and institutional accountability, especially in institutionally weaker or less democratic states.</p>
<p>However, one major limitation in this literature, at least as to how sanctions are actually operationalized, is that much of the existing work, including Dreher, Gassebner, and Siemers (2017) <span class="citation" data-cites="dreher2017">(<a href="#ref-dreher2017" role="doc-biblioref">Dreher, Gassebner, and Siemers 2017</a>)</span>, Hufbauer et al.&nbsp;(2007) [<span class="citation" data-cites="hufbauer2007">Hufbauer et al. (<a href="#ref-hufbauer2007" role="doc-biblioref">2007</a>)</span>], and Morgan, Bapat, and Kobayashi (2014) <span class="citation" data-cites="morgan2014">(<a href="#ref-morgan2014" role="doc-biblioref">Morgan, Bapat, and Kobayashi 2014</a>)</span>, relies primarily on binary indicators for whether a country is sanctioned or not. In practice, this means sanctions are often treated as roughly equivalent regardless of how economically disruptive they actually are, how long they persist, or how exposed a country is to trade in the first place. At the same time, these studies generally use similar country-level controls like GDP per capita, economic growth, trade openness, and political stability for the purpose of isolating institutional effects, but the sanctions treatment itself remains relatively blunt. As a result, the literature gives us a fairly strong understanding that sanctions matter, but much less understanding regarding whether stronger or more economically disruptive sanctions generate meaningfully different corruption outcomes.</p>
<p>Some work in the broader sanctions and trade literature has started moving toward more continuous measures of sanctions exposure. For example, Crozet and Hinz (2020) [<span class="citation" data-cites="crozet2020">Crozet and Hinz (<a href="#ref-crozet2020" role="doc-biblioref">2020</a>)</span>] and Felbermayr et al.&nbsp;(2020) <span class="citation" data-cites="felbermayr2020">(<a href="#ref-felbermayr2020" role="doc-biblioref">Felbermayr et al. 2020</a>)</span> measure sanctions in terms of trade losses or reductions in economic flows, while other studies incorporate duration or financial restrictions as proxies for sanctions intensity. However, these approaches have rarely been applied directly to corruption outcomes specifically, and there remains relatively limited work constructing a continuous sanctions-intensity measure that jointly captures both exposure and duration when studying corruption.</p>
<p>This project attempts to address that gap by constructing a sanctions-intensity measure scaled by pre-sanction trade openness and sanction duration, for the purpose of capturing not just whether sanctions exist, but also the extent to which they plausibly disrupt the economy over time. Rather than asking only whether sanctions increase corruption, the analysis instead examines whether more economically disruptive sanctions generate different corruption effects across regime types. In doing so, the project attempts to extend the existing sanctions-corruption literature by moving beyond binary sanctions indicators and toward a more continuous measure of sanctions exposure, persistence, and economic disruption.</p>
</section>
</section>
<section id="theory-and-hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="theory-and-hypotheses">(2) Theory and Hypotheses</h2>
<p>I shall test for two hypothesis:&nbsp;</p>
<p><strong>i) U.S. economic sanctions on average increase corruption from 2003-2023 in recipient countries.</strong></p>
<p><strong>ii)) US economic sanctions will increase corruption more strongly in autocracies and weaker or negative effects in democracies.</strong></p>
<p>The impact of economic sanctions on corruption does not have a single clear mechanism, either intuitively or empirically. Existing research suggests two competing pathways. In cash-strapped and institutionally weak countries, sanctions may worsen corruption by reducing trade and economic growth, shifting activity into informal and illicit markets (Afesorgbor and Mahadevan 2016; Neuenkirch and Neumeier 2016)<span class="citation" data-cites="neuenkirch2016">(<a href="#ref-neuenkirch2016" role="doc-biblioref">Neuenkirch and Neumeier 2016</a>)</span>. Under these conditions, political elites retain centralized control over scarce resources such as import licenses and foreign currency, allowing them to distribute access selectively in exchange for bribes. Empirical evidence supports this mechanism, showing that sanctions are associated with higher corruption levels, particularly in countries with weaker institutional constraints (Dreher, Gassebner, and Siemers 2017)<span class="citation" data-cites="dreher2017">(<a href="#ref-dreher2017" role="doc-biblioref">Dreher, Gassebner, and Siemers 2017</a>)</span>. Sanctions also often generate evasion networks reliant on bribery and informal exchange, further embedding corruption into state structures (Early 2015). At the same time, democratic systems may react differently. Where institutions impose greater accountability and transparency, sanctions can trigger reforms, external monitoring, and tighter oversight. Recent research finds that under these conditions corruption can decline over time (Gutmann, Langer, and Neumeier 2024).</p>
<p>However, much of the existing literature treats sanctions as binary, measuring only whether a sanction exists in a given country-year<span class="citation" data-cites="dreher2017">(<a href="#ref-dreher2017" role="doc-biblioref">Dreher, Gassebner, and Siemers 2017</a>)</span>, <span class="citation" data-cites="hufbauer2007">(<a href="#ref-hufbauer2007" role="doc-biblioref">Hufbauer et al. 2007</a>)</span> <span class="citation" data-cites="morgan2014">(<a href="#ref-morgan2014" role="doc-biblioref">Morgan, Bapat, and Kobayashi 2014</a>)</span>. I extend this approach by focusing on sanction intensity rather than sanction presence alone. My argument is that increases in sanction intensity should increase corruption more strongly in autocracies than in democracies because intensity better captures the extent to which sanctions actually disrupt the economy. A marginal increase in sanction intensity, through greater trade exposure or longer duration, should amplify scarcity and economic distortions more severely in autocratic systems, where weaker institutions and lower oversight allow officials to exploit these conditions through rent-seeking, informal markets, and untracked transactions. Democratic regimes, by contrast, possess stronger institutional checks, greater transparency, and higher accountability, which may dampen how much these economic shocks translate into corruption and, in some cases, may even reduce corruption through reforms or tighter enforcement. Thus, the same increase in sanction intensity should have a smaller or more muted effect in democracies. To address reverse causality, I also implement placebo tests using led sanctions as a predictor to test whether sanctions are simply responding to already rising corruption levels rather than causing them. Therefore, the main hypothesis of interest is the second hypothesis on heterogeneous regime-type effects of sanctions on corruption.</p>
</section>
<section id="research-design" class="level2">
<h2 class="anchored" data-anchor-id="research-design">(3) Research Design</h2>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<p>This project uses a country-year panel from 2003 to 2023 to estimate the relationship between unilateral U.S. trade sanctions and political corruption. The unit of observation is the country-year. The outcome variable, sanctions variables, and country-level covariates are drawn from cross-national datasets that provide annual coverage across most sovereign states.</p>
<p><strong>V-Dem Political Corruption Index</strong> The dependent variable of corruption is pulled from the V-Dem Political Corruption Index (v2x_corr column). This index measures the pervasiveness of political corruption across multiple state institutions and expert-coded integrators via panel analysis. V-Dem constructs the index from indicators covering corrupt activity in the legislature, judiciary, executive, and public sector. This composition makes the index appropriate for this study because the theorized mechanisms linking sanctions to corruption operate through political and administrative channels.</p>
<p><strong>U.S.-Only Trade Sanctions (Global Sanctions Database)</strong><span class="citation" data-cites="felbermayr2020">(<a href="#ref-felbermayr2020" role="doc-biblioref">Felbermayr et al. 2020</a>)</span><strong>:</strong> The main independent variable is a U.S.-only trade sanctions indicator, constructed from the Global Sanctions DataBase. The GSDB records sanctions by sender, target, year, sanction type, political objective, and success. I restrict the sanctions data to cases where the United States is the sole sender to form the treatment, or the country has been sanctioned in the past by any actor to eliminate 0-heavy sample. I also hone my sample down to where the sanction type is trade-related, as trade sanctions and resource-related channels are my mechanisms of interest, especially in their plausible relation to rent-seeking and corruption. The GSDB is well suited for this construction because it explicitly distinguishes bilateral, multilateral, and plurilateral sanctions and classifies sanctions by type, including trade sanctions, financial sanctions, travel restrictions, arms sanctions, military assistance sanctions, and other sanctions.</p>
<p><strong>EIU Democracy Index:</strong> Regime type is measured using the Economist Intelligence Unit Democracy Index, which scores countries from 0 to 10 using 60 indicators across five categories: electoral process and pluralism, functioning of government, political participation, political culture, and civil liberties. This aggregate will serve as an important control and mechanism for heterogenous effects of sanctions on corruption.</p>
<p><strong>GDP Growth &amp; Log GDP per Capita (World Bank WDI):</strong> Economic conditions are measured using World Bank World Development Indicators. GDP growth captures annual changes in output, while log GDP per capita captures development level. GDP per capita is logged because income is highly skewed across countries, and the transformation reduces the influence of extreme high-income observations.</p>
<p><strong>Trade Openness (World Bank WDI):</strong> Trade exposure is measured as a component into Sanction Intensity through the variable OneYearLaggedTradeOpenness, based on the WDI trade openness variable: exports plus imports of goods and services as a percentage of GDP.</p>
<p><strong>Political Stability (World Bank WGI):</strong> Political instability is measured using the World Bank Political Stability and Absence of Violence/Terrorism estimate. This variable captures perceived risks of government destabilization and politically motivated violence, including terrorism. It is used as an annual measure of domestic instability and security risk. It takes into account survey-based risks like political violence, terrorism, armed conflict, coups, social unrest, government collapse, ethnic/religious tensions, and internal/external conflict risks.</p>
</section>
<section id="sample" class="level3">
<h3 class="anchored" data-anchor-id="sample">Sample</h3>
<p>The final sample is constructed as a country-year panel covering 2003–2023 using sovereign states with available data on corruption, sanctions, democracy, and macroeconomic controls. However, rather than using all countries globally, I restrict the analysis to ever-sanctioned countries, meaning countries that experienced sanctions by at least one sender at some point during the 2003–2023 period. I do this because including large numbers of never-sanctioned country-years would create an extremely zero-heavy sample dominated by structurally different countries unlikely to ever face sanctions exposure, which could bias the regression toward mechanically finding little meaningful relationship. Instead, the identifying comparison becomes sanctioned years versus non-sanctioned years within countries realistically exposed to sanctions risk, creating a more credible counterfactual and improving comparability across observations. Country-years are dropped when key variables are missing, primarily V-Dem corruption measures, EIU democracy scores, WDI macroeconomic controls, or sanction classification information from the GSDB. The main two-way fixed effects specification contains 512 observations. Once country-specific time trends are added as a robustness check, the usable sample remains broadly similar but loses additional identifying variation because estimation now relies on within-country deviations from each country’s own corruption trajectory over time. The placebo specification using a two-year lead of sanctions intensity falls further to 448 observations, a drop of 64 country-years, because constructing future sanctions exposure mechanically removes later observations without forward temporal coverage. Importantly, these drops are not concentrated only among treated observations, but largely reflect missing covariate availability and the temporal requirements created by lagged and lead specifications across both sanctioned and non-sanctioned years within ever-sanctioned countries.</p>
</section>
<section id="variables" class="level3">
<h3 class="anchored" data-anchor-id="variables">Variables</h3>
<p>The data mentioned renders into the variables constructed as follows: My dependent variable, Corruption_{it}, is measured using V-Dem’s Political Corruption Index (v2x_corr), which captures corruption across the executive, legislature, judiciary, and public sector. This aligns closely with the project’s focus on elite rent-seeking, patronage networks, and institutional misuse of power rather than only petty bribery. My main independent variable, <span class="math display">\[SanctionIntensity_{it}\]</span>, is a one-year-lagged U.S.-only trade sanction indicator from the Global Sanctions Database (GSDB). I use two sanctions measures. The first is <span class="math display">\[SanctionDummy_{it}\]</span>, a binary indicator equal to one for country-years in which a U.S.-only trade sanction is active and zero otherwise. The second is <span class="math display">\[SanctionIntensity_{it}\]</span>, which is designed to capture both cumulative sanctions exposure and a country’s susceptibility to sanctions pressure. I construct this measure by identifying the start year of each sanction episode and calculating the number of consecutive years the sanction remains active in each country-year, producing a <span class="math display">\[Duration_{it}\]</span> component. I then define <span class="math display">\[SanctionIntensity_{it}\]</span> as the lagged <span class="math display">\[SanctionDummy_{it}\]</span> multiplied by <span class="math display">\[OneYearLaggedTradeOpenness_{it}\]</span> and logged <span class="math display">\[Duration_{it}\]</span>. Using <span class="math display">\[OneYearLaggedTradeOpenness_{it}\]</span> avoids incorporating contemporaneous trade flows already affected by sanctions themselves within the sanction intensity measure (and thus avoiding a post-treatment control/bad control problem), while the logged duration term captures diminishing marginal effects from prolonged sanctions exposure. This intensity measure extends past recent sanctions literature, which commonly relies on binary sanction indicators without incorporating exposure, persistence, or lifecycle effects. However, it shall be noted that sanction intensity as a measure is picking up speed as a measure in the literature not related to corruption, thus it holds as a viable apprpach towards adding more nuance to a sanction and its impacts.</p>
<p>I include DemocracyScore_{it} to test regime-type heterogeneity, since recent literature suggests sanctions may operate differently across democratic and autocratic accountability structures. GDPGrowth_{it} and LogGDPpc_{it} control for economic shocks and development levels, both of which are consistently associated with corruption and institutional quality in the broader literature and are commonly included in recent sanctions-corruption work. I also include <span class="math display">\[PolStability_{it}\]</span> to account for violence, terrorism risk, coups, and internal instability, since these factors may independently influence both sanction selection and corruption outcomes. Country fixed effects, represented by <span class="math display">\[\alpha_t \]</span>, absorb time-invariant country characteristics, while year fixed effects, represented by <span class="math display">\[\delta_t\]</span>, absorb common global shocks affecting all countries in a given year. Country-specific linear time trends are later additionally included as a robustness check for differential pre-existing corruption trajectories across countries over time.</p>
<p>The mean, median, mode, range and standard deviation of the variables are summarized in the table below (Figure 3.1)</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary Statistics</caption>
<colgroup>
<col style="width: 38%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Minimum</th>
<th style="text-align: right;">Maximum</th>
<th style="text-align: right;">Range</th>
<th style="text-align: right;">Standard Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Corruption</td>
<td style="text-align: right;">0.554</td>
<td style="text-align: right;">0.004</td>
<td style="text-align: right;">0.965</td>
<td style="text-align: right;">0.961</td>
<td style="text-align: right;">0.297</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sanction Dummy</td>
<td style="text-align: right;">0.104</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">0.305</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sanction Intensity</td>
<td style="text-align: right;">31.966</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">456.021</td>
<td style="text-align: right;">456.021</td>
<td style="text-align: right;">74.765</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sanction Duration</td>
<td style="text-align: right;">0.888</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">61.000</td>
<td style="text-align: right;">61.000</td>
<td style="text-align: right;">4.532</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Democracy Score</td>
<td style="text-align: right;">5.298</td>
<td style="text-align: right;">0.260</td>
<td style="text-align: right;">9.930</td>
<td style="text-align: right;">9.670</td>
<td style="text-align: right;">2.132</td>
</tr>
<tr class="even">
<td style="text-align: left;">GDP Growth</td>
<td style="text-align: right;">3.592</td>
<td style="text-align: right;">-50.339</td>
<td style="text-align: right;">86.827</td>
<td style="text-align: right;">137.165</td>
<td style="text-align: right;">5.834</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Log GDP per Capita</td>
<td style="text-align: right;">4.040</td>
<td style="text-align: right;">2.996</td>
<td style="text-align: right;">5.163</td>
<td style="text-align: right;">2.167</td>
<td style="text-align: right;">0.508</td>
</tr>
<tr class="even">
<td style="text-align: left;">Political Stability</td>
<td style="text-align: right;">-0.349</td>
<td style="text-align: right;">-2.711</td>
<td style="text-align: right;">1.496</td>
<td style="text-align: right;">4.207</td>
<td style="text-align: right;">0.875</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Trade Openness</td>
<td style="text-align: right;">76.504</td>
<td style="text-align: right;">2.474</td>
<td style="text-align: right;">258.780</td>
<td style="text-align: right;">256.307</td>
<td style="text-align: right;">38.311</td>
</tr>
<tr class="even">
<td style="text-align: left;">One Year Lagged Trade Openness</td>
<td style="text-align: right;">79.471</td>
<td style="text-align: right;">14.578</td>
<td style="text-align: right;">242.361</td>
<td style="text-align: right;">227.783</td>
<td style="text-align: right;">50.321</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Figure 3.1</p>
<p><strong>Notes</strong>: These summary statistics are important for interpreting later regression results because the variables operate on quite different scales. <em>Corruption</em> is measured on V-Dem’s standardized 0–1 index, while <em>SanctionIntensity</em> is a constructed exposure measure combining sanction status, lagged trade openness, and sanction duration. The large spread in SanctionIntensity and duration reflects that most country-years face no sanctions, while a smaller subset experience prolonged sanctions exposure. This also helps justify the use of logged duration to account for diminishing effects and the later lead placebo tests as sanctions on average last one year, so a proper placebo test would lean towards a two-year lead specification used to test whether future sanctions exposure predicts current corruption outcomes through pre-existing trends rather than a true sanctions effect.</p>
</section>
</section>
<section id="estimation-methodology" class="level2">
<h2 class="anchored" data-anchor-id="estimation-methodology">Estimation Methodology</h2>
<section id="primary-testregression-figure-3.2" class="level3">
<h3 class="anchored" data-anchor-id="primary-testregression-figure-3.2">Primary Test/Regression (Figure 3.2)</h3>
<p><span class="math display">\[
Corruption_{it}
=
\alpha_i + \delta_t
+ \beta_1 SanctionIntensity_{it}
+ \beta_2 DemocracyScore_{it}
+ \beta_3 \left(SanctionIntensity_{it} \times DemocracyScore_{it}\right)
+ \beta_4 GDPGrowth_{it}
+ \beta_5 LogGDPpc_{it}
+ \beta_6 PolStability_{it}
+ \varepsilon_{it}
\]</span></p>
<p>where</p>
<p><span class="math display">\[
SanctionIntensity_{it}
=
SanctionDummy_{it}
\times OneYear Lagged TradeOpenness_{it}
\times \log(1 + Duration_{it})
\]</span></p>
<ul>
<li><p><span class="math inline">\(Corruption_{it}\)</span>: the V-Dem Political Corruption Index score for country <span class="math inline">\(i\)</span> in year <span class="math inline">\(t\)</span>. Higher values indicate more political corruption.</p></li>
<li><p><span class="math inline">\(\alpha_i\)</span>: <strong>country fixed effects</strong>, which absorb time-invariant characteristics of country <span class="math inline">\(i\)</span>, such as geography, legal origins, colonial history, and persistent institutional traits.</p></li>
<li><p><span class="math inline">\(\delta_t\)</span>: <strong>year fixed effects</strong>, which absorb common shocks affecting all countries in year <span class="math inline">\(t\)</span>, such as global recessions, commodity shocks, or broad changes in international sanctions policy.</p></li>
<li><p><span class="math inline">\(SanctionIntensity_{it}\)</span>: the continuous sanction-intensity measure for country <span class="math inline">\(i\)</span> in year <span class="math inline">\(t\)</span>. It increases when a country was under a <strong>U.S.-only trade sanction in the previous year</strong>, when the country had higher pre-sanction trade exposure, and when the sanction episode has lasted longer.</p></li>
<li><p><span class="math inline">\(SanctionDummy_{it}\)</span>: an indicator equal to 1 if country <span class="math inline">\(i\)</span> was subject to a <strong>US-only trade sanction</strong> in the previous year, and 0 otherwise. I lag this variable by one year so sanction exposure precedes the corruption outcome, following recent sanctions-corruption work that uses lagged sanctions to reduce reverse-causality concerns. <span class="citation" data-cites="gutmann2026">(<a href="#ref-gutmann2026" role="doc-biblioref">Gutmann, Neuenkirch, and Neumeier 2026</a>)</span></p></li>
<li><p><span class="math inline">\(log(1+Duration_{it})\)</span>: the number of years the relevant US-only trade sanction episode has been active, shifted forward one year to match the lagged sanction timing. I use duration because longer sanction episodes may operate differently than short sanctions, especially if institutional and corruption responses emerge over time. I also take the logarithm to account for diminishing marginal effects of sanctions over the time of their imposition (Escribà-Folch and Wright 2004) <span class="citation" data-cites="escriba2004">(<a href="#ref-escriba2004" role="doc-biblioref">Escribà-Folch and Wright 2004</a>)</span>.</p></li>
<li><p><span class="math inline">\(OneYearLaggedTradeOpenness_{it}\)</span>: the country’s trade openness before sanction exposure, measured as imports plus exports as a share of GDP. I include it in the construction of <span class="math inline">\(SanctionIntensity_{it}\)</span> because trade sanctions should matter more for countries more exposed to trade, while using lagged trade openness avoids using trade flows already affected by sanctions.</p></li>
<li><p><span class="math inline">\(DemocracyScore_{it}\)</span>: the EIU Democracy Index score for country <span class="math inline">\(i\)</span> in year <span class="math inline">\(t\)</span>. I include this because regime type is central to the hypothesis. Recent sanctions-corruption work separates sanction effects by democracies and autocracies, since accountability and institutional constraints may change how sanctions affect corruption( Gutmann et al) <span class="citation" data-cites="gutmann2026">(<a href="#ref-gutmann2026" role="doc-biblioref">Gutmann, Neuenkirch, and Neumeier 2026</a>)</span>.</p></li>
<li><p><span class="math inline">\(SanctionIntensity_{it} \times DemocracyScore_{it}\)</span>: the interaction term between sanction intensity and democracy score. I include this to test whether the effect of sanction intensity on corruption significantly varies by regime type.</p></li>
<li><p><span class="math inline">\(GDPGrowth_{it}\)</span>: annual GDP growth for country <span class="math inline">\(i\)</span> in year <span class="math inline">\(t\)</span>. I include this to control for short-run economic shocks, since economic downturns may affect both corruption and the likelihood of sanctions.</p></li>
<li><p><span class="math inline">\(LogGDPpc_{it}\)</span>: the logarithm of GDP per capita for country <span class="math inline">\(i\)</span> in year <span class="math inline">\(t\)</span>. I include this because economic development is a standard predictor of corruption. Gutmann et al.&nbsp;specifically note that real GDP per capita is the only control with a consistent effect across their corruption specifications, with more developed countries displaying lower corruption. (Gutmann et al.&nbsp;2026, Treisman et al.&nbsp;2000) <span class="citation" data-cites="gutmann2026 treisman2000">(<a href="#ref-gutmann2026" role="doc-biblioref">Gutmann, Neuenkirch, and Neumeier 2026</a>; <a href="#ref-treisman2000" role="doc-biblioref">Treisman 2000</a>)</span></p></li>
<li><p><span class="math inline">\(PolStability_{it}\)</span>: the <strong>Political Stability and Absence of Violence/Terrorism</strong> score for country <span class="math inline">\(i\)</span> in year <span class="math inline">\(t\)</span>. I include this because instability, violence, coups, and terrorism risk may both make US sanctions more likely and independently affect corruption. Recent sanctions-corruption work also emphasizes that sanctioned countries differ from non-sanctioned ones in conflict exposure, making these political-security controls important for selection concerns. <span class="citation" data-cites="pellegrini2008 dreher2017">(<a href="#ref-pellegrini2008" role="doc-biblioref">Pellegrini and Gerlagh 2008</a>; <a href="#ref-dreher2017" role="doc-biblioref">Dreher, Gassebner, and Siemers 2017</a>)</span></p></li>
<li><p><span class="math inline">\(\varepsilon_{it}\)</span>: the error term.</p></li>
</ul>
<p>The marginal effect of sanction intensity on corruption is therefore:</p>
<p><span class="math display">\[
\frac{\partial Corruption_{it}}{\partial SanctionIntensity_{it}}
=
\beta_1 + \beta_3 DemocracyScore_{it}
\]</span></p>
<p>This implies that the effect of sanction intensity is allowed to vary systematically across regime types, which we display later in figure 3.2</p>
</section>
<section id="endogeneity-concerns-and-remaining-confounders" class="level3">
<h3 class="anchored" data-anchor-id="endogeneity-concerns-and-remaining-confounders">Endogeneity Concerns and Remaining Confounders</h3>
<p>To reflect on the clear issue of endogeneity since my hypothesis is causal, the primary concern is that U.S. sanctions are not randomly assigned for a multitude of reasons. First, the United States is more likely to sanction countries after political, security, or economic shocks that may themselves affect corruption <span class="citation" data-cites="kwon2025growth">(<a href="#ref-kwon2025growth" role="doc-biblioref">Kwon, Syropoulos, and Yotov 2025</a>)</span>. Lagging sanctions to fend off this threat of reverse causation reflects these concerns, though many confounders of this economic/political shock susceptibility remain. This is because even after controlling for country fixed effects as well as controlling for year fixed effects, time varying factors remain, in other words, the very idiosyncratic shocks we wich to control away. For example,coups, democratic backsliding, conflict, terrorism concerns, geopolitical realignment, and macroeconomic crises could all increase the probability of a U.S.-only sanction, whilst also generally increasing corruption through channels such as increasing patronage, emergency procurement, smuggling, weakened courts, elite rent-seeking, or reduced oversight. I try to reduce this concern by controlling for proxies of these behaviors like GDP growth, log GDP per capita, democracy score, and political stability (Pellegrini and Gerlagh 2008, Treisman 2000) <span class="citation" data-cites="pellegrini2008">(<a href="#ref-pellegrini2008" role="doc-biblioref">Pellegrini and Gerlagh 2008</a>)</span> <span class="citation" data-cites="treisman2000">(<a href="#ref-treisman2000" role="doc-biblioref">Treisman 2000</a>)</span>.</p>
<p>Still, some important threats to causality remain as unobserved variables, especially U.S. strategic motives, security designations, resource politics, etc. Also, it is critically important to account for pre-existing corruption trajectories. Without all the aforementioned confounders accounted for, our identifying assumption is that, after fixed effects and controls, changes in U.S.-only sanction intensity are not driven by unobserved time-varying shocks that also directly affect corruption. That is a strong assumption whether that be to <em>causally</em> confirm or reject the hypotheses.&nbsp;</p>
<p>To further confirm (or deny) causality in sanctions causing corruption, my primary robustness check and empirical extension is a lead-placebo test using sanctions imposed two years in the future as the independent variable. If future sanctions predict current corruption, this would suggest that sanctions are responding to pre-existing political or economic deterioration rather than causing subsequent corruption, (reverse causality, and also other factors impacting both sanctions and corruption).</p>
<p>However, it is important to note that these confounders quite broadly bias the relationship in the direction of a positive correlation. In other words, if the U.S.-only sanctions are triggered by coups, conflict, terrorism concerns, drug trafficking, resource shocks, democratic backsliding, or geopolitical realignment (controls we do not account for and thus may actively confound) those same shocks should generally increase political corruption through weaker oversight, emergency procurement, smuggling, patronage, and elite rent-seeking. However, Figure 3.2 shows our regression without controls of pre-existing time trends posits a significant negative relationship among sanctions on corruption. Upon examination of possible drivers of this relationship in our sample, it shall be emphasized that some of the highest-intensity observations are relatively high-trade or institutionally stronger cases, including mid-democratic countries such as Ireland, where V-Dem political corruption is already low or declining. This matters because my intensity measure uses pre-sanction trade openness and sanction duration, so high intensity does not only mean a politically severe sanction, it also reflects high baseline trade exposure and long sanction duration. Thus, pre-existing downward corruption trends may partly drive the contrarian negative relationship. Hence, I choose to include a robustness check by adding country-specific linear time trends to the main regression (Figure 3.3). The results of this robustness check, as we will observe, severely hinder the significance of our test. Given my existing controls in addition to pre-existing corruption time-trends which absorb the significant relationship, additional controls likely would not control for confounders in a meaningful way (and sample size would be further reduced due to incomplete data).</p>
</section>
</section>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">(4) Findings</h2>
<section id="relationship-among-us-sanctions-and-corruption-without-controls" class="level3">
<h3 class="anchored" data-anchor-id="relationship-among-us-sanctions-and-corruption-without-controls">Relationship Among US Sanctions and Corruption (without controls)</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SANCTION-V3_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SANCTION-V3_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 4.1 (Top) &amp; Figure 4.2 (Bottom)</p>
<section id="note-figure-4.1-plots-v-dem-political-corruption-scores-by-whether-a-country-year-is-under-a-us-only-trade-sanction.-the-0-category-represents-country-years-without-a-u.s.-only-trade-sanction-but-have-been-sanctioned-in-other-country-years-while-the-1-category-represents-country-years-with-one.-since-the-v-dem-political-corruption-index-is-scaled-so-that-higher-values-reflect-more-corruption-the-figure-does-not-show-the-simple-raw-pattern-i-would-expect-if-sanctions-were-clearly-associated-with-more-corruption.-instead-sanctioned-country-years-have-a-lower-median-corruption-score-than-non-sanctioned-country-years-even-though-the-two-distributions-overlap-heavily.-thus-the-sanction-dummy-alone-does-not-visually-support-my-hypothesis-i.-figure-4.2-is-the-continuous-sanction-intensity-measure.-this-plot-asks-a-whether-greater-sanction-exposure-is-associated-with-different-levels-of-political-corruption.-the-fitted-line-slopes-downward-meaning-higher-sanction-intensity-is-associated-with-lower-observed-v-dem-political-corruption-scores-in-the-raw-bivariate-relationship.-this-again-does-not-veer-in-the-direction-of-supporting-my-hypothesis-i-that-sanctions-increase-corruption-on-average.-however-the-graph-is-still-useful-because-it-shows-that-the-relationship-is-not-obvious-from-the-raw-data-and-cannot-be-treated-as-a-simple-sanctions-on-corruption-up-story.-most-observations-are-clustered-at-low0-sanction-intensity-by-the-way-the-sanction-intensity-measure-is-built-based-off-the-dummy-and-because-there-is-a-heavier-amount-of-country-years-not-enduring-a-us-specific-sanction-just-by-natural-data.-there-is-also-wide-variation-in-corruption-outcomes-among-those-observations." class="level5">
<h5 class="anchored" data-anchor-id="note-figure-4.1-plots-v-dem-political-corruption-scores-by-whether-a-country-year-is-under-a-us-only-trade-sanction.-the-0-category-represents-country-years-without-a-u.s.-only-trade-sanction-but-have-been-sanctioned-in-other-country-years-while-the-1-category-represents-country-years-with-one.-since-the-v-dem-political-corruption-index-is-scaled-so-that-higher-values-reflect-more-corruption-the-figure-does-not-show-the-simple-raw-pattern-i-would-expect-if-sanctions-were-clearly-associated-with-more-corruption.-instead-sanctioned-country-years-have-a-lower-median-corruption-score-than-non-sanctioned-country-years-even-though-the-two-distributions-overlap-heavily.-thus-the-sanction-dummy-alone-does-not-visually-support-my-hypothesis-i.-figure-4.2-is-the-continuous-sanction-intensity-measure.-this-plot-asks-a-whether-greater-sanction-exposure-is-associated-with-different-levels-of-political-corruption.-the-fitted-line-slopes-downward-meaning-higher-sanction-intensity-is-associated-with-lower-observed-v-dem-political-corruption-scores-in-the-raw-bivariate-relationship.-this-again-does-not-veer-in-the-direction-of-supporting-my-hypothesis-i-that-sanctions-increase-corruption-on-average.-however-the-graph-is-still-useful-because-it-shows-that-the-relationship-is-not-obvious-from-the-raw-data-and-cannot-be-treated-as-a-simple-sanctions-on-corruption-up-story.-most-observations-are-clustered-at-low0-sanction-intensity-by-the-way-the-sanction-intensity-measure-is-built-based-off-the-dummy-and-because-there-is-a-heavier-amount-of-country-years-not-enduring-a-us-specific-sanction-just-by-natural-data.-there-is-also-wide-variation-in-corruption-outcomes-among-those-observations.">Note: Figure 4.1 plots V-Dem political corruption scores by whether a country-year is under a US-only trade sanction. The 0 category represents country-years without a U.S.-only trade sanction (but have been sanctioned in other country-years), while the 1 category represents country-years with one. Since the V-Dem political corruption index is scaled so that higher values reflect more corruption, the figure does not show the simple raw pattern I would expect if sanctions were clearly associated with more corruption. Instead, sanctioned country-years have a lower median corruption score than non-sanctioned country-years, even though the two distributions overlap heavily. Thus, the sanction dummy alone does not visually support my hypothesis (i). Figure 4.2 is the continuous sanction intensity measure. This plot asks a whether greater sanction exposure is associated with different levels of political corruption. The fitted line slopes downward, meaning higher sanction intensity is associated with lower observed V-Dem political corruption scores in the raw bivariate relationship. This again does not veer in the direction of supporting my hypothesis (i) that sanctions increase corruption on average. However, the graph is still useful because it shows that the relationship is not obvious from the raw data and cannot be treated as a simple sanctions-on, corruption-up story. Most observations are clustered at low/0 sanction intensity by the way the sanction intensity measure is built based off the dummy, and because there is a heavier amount of country years not enduring a US specific sanction just by natural data. There is also wide variation in corruption outcomes among those observations.</h5>
</section>
</section>
<section id="primary-test-regression-findings-results-of-figure-3.2" class="level3">
<h3 class="anchored" data-anchor-id="primary-test-regression-findings-results-of-figure-3.2">Primary Test/ Regression Findings (Results of Figure 3.2)</h3>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_n9lb93711o5gvhfapou3 = TinyTable.createTableFunctions("tinytable_n9lb93711o5gvhfapou3");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '22', j: 2 } ], css_id: 'tinytable_css_d5pe1hgfetpggw1ycewm',}, 
          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_ak33p9gmbk15fjkpds63',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '21', j: 2 } ], css_id: 'tinytable_css_mcu5n29s22tdczi9wfdr',}, 
          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_orh8f6h4hcg7wl111rfp',}, 
          { positions: [ { i: '22', j: 1 } ], css_id: 'tinytable_css_zqyoan55ske16u1jq941',}, 
          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_7vj7gk4zjoxlb7m2omz2',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 }, { i: '21', j: 1 } ], css_id: 'tinytable_css_7ixhtf7p1gey9ogugo2t',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_aa4cduuwumwtaek5ye3d',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_n9lb93711o5gvhfapou3.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_n9lb93711o5gvhfapou3 td.tinytable_css_d5pe1hgfetpggw1ycewm, #tinytable_n9lb93711o5gvhfapou3 th.tinytable_css_d5pe1hgfetpggw1ycewm {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_n9lb93711o5gvhfapou3 td.tinytable_css_ak33p9gmbk15fjkpds63, #tinytable_n9lb93711o5gvhfapou3 th.tinytable_css_ak33p9gmbk15fjkpds63 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_n9lb93711o5gvhfapou3 td.tinytable_css_mcu5n29s22tdczi9wfdr, #tinytable_n9lb93711o5gvhfapou3 th.tinytable_css_mcu5n29s22tdczi9wfdr { text-align: center }
    #tinytable_n9lb93711o5gvhfapou3 td.tinytable_css_orh8f6h4hcg7wl111rfp, #tinytable_n9lb93711o5gvhfapou3 th.tinytable_css_orh8f6h4hcg7wl111rfp {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_n9lb93711o5gvhfapou3 td.tinytable_css_zqyoan55ske16u1jq941, #tinytable_n9lb93711o5gvhfapou3 th.tinytable_css_zqyoan55ske16u1jq941 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_n9lb93711o5gvhfapou3 td.tinytable_css_7vj7gk4zjoxlb7m2omz2, #tinytable_n9lb93711o5gvhfapou3 th.tinytable_css_7vj7gk4zjoxlb7m2omz2 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_n9lb93711o5gvhfapou3 td.tinytable_css_7ixhtf7p1gey9ogugo2t, #tinytable_n9lb93711o5gvhfapou3 th.tinytable_css_7ixhtf7p1gey9ogugo2t { text-align: left }
    #tinytable_n9lb93711o5gvhfapou3 td.tinytable_css_aa4cduuwumwtaek5ye3d, #tinytable_n9lb93711o5gvhfapou3 th.tinytable_css_aa4cduuwumwtaek5ye3d {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_n9lb93711o5gvhfapou3" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="2">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">sanction_intensity</td>
                  <td data-row="1" data-col="2">-0.00026**</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.00010)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">democracy_score</td>
                  <td data-row="3" data-col="2">-0.02188***</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.00527)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">gdp_growth</td>
                  <td data-row="5" data-col="2">0.00024</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.00061)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">log_gdppc</td>
                  <td data-row="7" data-col="2">0.16894***</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.04585)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">pol_stability</td>
                  <td data-row="9" data-col="2">-0.01547+</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.00817)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">sanction_intensity × democracy_score</td>
                  <td data-row="11" data-col="2">0.00003*</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2">(0.00001)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">Num.Obs.</td>
                  <td data-row="13" data-col="2">512</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1">R2</td>
                  <td data-row="14" data-col="2">0.980</td>
                </tr>
                <tr>
                  <td data-row="15" data-col="1">R2 Adj.</td>
                  <td data-row="15" data-col="2">0.978</td>
                </tr>
                <tr>
                  <td data-row="16" data-col="1">R2 Within</td>
                  <td data-row="16" data-col="2">0.082</td>
                </tr>
                <tr>
                  <td data-row="17" data-col="1">R2 Within Adj.</td>
                  <td data-row="17" data-col="2">0.070</td>
                </tr>
                <tr>
                  <td data-row="18" data-col="1">AIC</td>
                  <td data-row="18" data-col="2">-1771.8</td>
                </tr>
                <tr>
                  <td data-row="19" data-col="1">BIC</td>
                  <td data-row="19" data-col="2">-1547.2</td>
                </tr>
                <tr>
                  <td data-row="20" data-col="1">RMSE</td>
                  <td data-row="20" data-col="2">0.04</td>
                </tr>
                <tr>
                  <td data-row="21" data-col="1">FE: country</td>
                  <td data-row="21" data-col="2">X</td>
                </tr>
                <tr>
                  <td data-row="22" data-col="1">FE: year</td>
                  <td data-row="22" data-col="2">X</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<p>Figure 4.3</p>
<p>The regression results above (Figure 4.3) do not support the original hypothesis that sanctions increase corruption on average (hypothesis i) or that this effect is strongest in autocracies (hypothesis ii). Instead, the estimated relationship moves in the opposite direction. The coefficient on sanction_intensity is negative and statistically significant at the 1 percent level (β = -0.00026, p &lt; 0.01), while the interaction term between sanction_intensity and democracy_score is positive and statistically significant at the 5 percent level (β = 0.00003, p &lt; 0.05). Since the model includes an interaction term, the effect of sanction intensity depends on democracy level:</p>
<p><span class="math display">\[
\frac{\partial Corruption}{\partial SanctionIntensity}=-0.00026 + (0.00003 \times DemocracyScore)\]</span></p>
<p>This means sanction intensity is associated with (as we will interpret not causally via the many possible confounders we mentioned and not yet accounting for pre-existing time-trends of corruption) lower corruption outcomes in less democratic countries in a significant manner, but this negative relationship weakens as democracy increases and eventually approaches zero in highly democratic regimes. Thus, while the results do show statistically significant heterogeneous effects by regime type, a sanction of similar caliber is asscoiated with less corruption for more autocratic regimes, the converse of my hypothesis. Substantively, the magnitude is modest but meaningful. A 100-point increase in sanction_intensity is associated with roughly a 0.026 decrease in the corruption index in low-democracy countries. Relative to the sample standard deviation of corruption (0.297), this is about 9 percent of one standard deviation. Given that sanction_intensity ranges from 0 to over 456, large sanctions episodes could therefore correspond to substantial changes in corruption outcomes over time.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SANCTION-V3_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 4.4</p>
<p>The marginal-effects visualization above (Figure 4.4) further supports this interpretation. The estimated effect of sanction intensity remains statistically distinguishable from zero (significant) primarily at lower levels of democracy (below ~6) while the confidence interval increasingly overlaps with zero as democracy scores rise (insignificant). This suggests that the relationship is concentrated largely within less democratic regime (primarily mid level democracies where the confidence band is smallest) and weakens substantially in more democratic institutional settings. However, it is important to note that we hesitate towards attributing causality not only due to time varying confounders (that would hint at <em>increasing</em> sanctions and corruption, contrary to our result), but also due to the issue of preexisting corruption time-trends.</p>
<p>After controlling for country preexisting trends of corruption over the 2003-2023, we observe no significant effect of sanctions on corruption:</p>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_40a0qsvlaf1onowzncx1 = TinyTable.createTableFunctions("tinytable_40a0qsvlaf1onowzncx1");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '22', j: 2 } ], css_id: 'tinytable_css_lnenylhoaeqpa6pou78l',}, 
          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_j28ou3cnd8dtn2xxkkh9',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '21', j: 2 } ], css_id: 'tinytable_css_xem4ypc95jc9ylmo7s82',}, 
          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_v0a9vg0yqusao2u03z43',}, 
          { positions: [ { i: '22', j: 1 } ], css_id: 'tinytable_css_lz9e9j5gadlwjh5ossxn',}, 
          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_t57jllfaeinamxyffg9o',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 }, { i: '21', j: 1 } ], css_id: 'tinytable_css_2ylk1gnqrm28wzmb2wc9',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_hixtb18fjl374fd5ni03',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_40a0qsvlaf1onowzncx1.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_40a0qsvlaf1onowzncx1 td.tinytable_css_lnenylhoaeqpa6pou78l, #tinytable_40a0qsvlaf1onowzncx1 th.tinytable_css_lnenylhoaeqpa6pou78l {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_40a0qsvlaf1onowzncx1 td.tinytable_css_j28ou3cnd8dtn2xxkkh9, #tinytable_40a0qsvlaf1onowzncx1 th.tinytable_css_j28ou3cnd8dtn2xxkkh9 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_40a0qsvlaf1onowzncx1 td.tinytable_css_xem4ypc95jc9ylmo7s82, #tinytable_40a0qsvlaf1onowzncx1 th.tinytable_css_xem4ypc95jc9ylmo7s82 { text-align: center }
    #tinytable_40a0qsvlaf1onowzncx1 td.tinytable_css_v0a9vg0yqusao2u03z43, #tinytable_40a0qsvlaf1onowzncx1 th.tinytable_css_v0a9vg0yqusao2u03z43 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_40a0qsvlaf1onowzncx1 td.tinytable_css_lz9e9j5gadlwjh5ossxn, #tinytable_40a0qsvlaf1onowzncx1 th.tinytable_css_lz9e9j5gadlwjh5ossxn {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_40a0qsvlaf1onowzncx1 td.tinytable_css_t57jllfaeinamxyffg9o, #tinytable_40a0qsvlaf1onowzncx1 th.tinytable_css_t57jllfaeinamxyffg9o {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_40a0qsvlaf1onowzncx1 td.tinytable_css_2ylk1gnqrm28wzmb2wc9, #tinytable_40a0qsvlaf1onowzncx1 th.tinytable_css_2ylk1gnqrm28wzmb2wc9 { text-align: left }
    #tinytable_40a0qsvlaf1onowzncx1 td.tinytable_css_hixtb18fjl374fd5ni03, #tinytable_40a0qsvlaf1onowzncx1 th.tinytable_css_hixtb18fjl374fd5ni03 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_40a0qsvlaf1onowzncx1" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="2">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">sanction_intensity</td>
                  <td data-row="1" data-col="2">-0.00014</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.00010)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">democracy_score</td>
                  <td data-row="3" data-col="2">0.01759*</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.00775)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">gdp_growth</td>
                  <td data-row="5" data-col="2">0.00047</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.00058)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">log_gdppc</td>
                  <td data-row="7" data-col="2">-0.01332</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.09333)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">pol_stability</td>
                  <td data-row="9" data-col="2">-0.00330</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.01012)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">sanction_intensity × democracy_score</td>
                  <td data-row="11" data-col="2">0.00001</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2">(0.00002)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">Num.Obs.</td>
                  <td data-row="13" data-col="2">512</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1">R2</td>
                  <td data-row="14" data-col="2">0.986</td>
                </tr>
                <tr>
                  <td data-row="15" data-col="1">R2 Adj.</td>
                  <td data-row="15" data-col="2">0.984</td>
                </tr>
                <tr>
                  <td data-row="16" data-col="1">R2 Within</td>
                  <td data-row="16" data-col="2">0.025</td>
                </tr>
                <tr>
                  <td data-row="17" data-col="1">R2 Within Adj.</td>
                  <td data-row="17" data-col="2">0.011</td>
                </tr>
                <tr>
                  <td data-row="18" data-col="1">AIC</td>
                  <td data-row="18" data-col="2">-1894.4</td>
                </tr>
                <tr>
                  <td data-row="19" data-col="1">BIC</td>
                  <td data-row="19" data-col="2">-1534.2</td>
                </tr>
                <tr>
                  <td data-row="20" data-col="1">RMSE</td>
                  <td data-row="20" data-col="2">0.03</td>
                </tr>
                <tr>
                  <td data-row="21" data-col="1">FE: country</td>
                  <td data-row="21" data-col="2">X</td>
                </tr>
                <tr>
                  <td data-row="22" data-col="1">FE: year</td>
                  <td data-row="22" data-col="2">X</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<p>Figure 4.5</p>
<p>We observe that what was a significant effect on corruption by sanctions has become insignificant by a large margin (β = -0.00014, standard deviation = 0.00010) and the interaction term between <em>sanction_intensity</em> and <em>democracy_score</em> also loses significance. This lines up with the earlier concern raised in Section 3 (Endogeneity) from countries such as Ireland and several mid-democracy cases in the sample, where corruption levels were already trending downward prior to sanctions exposure. In other words, a meaningful portion of the earlier variation giving causal hope to the baseline model appears to have been driven by pre-existing institutional trajectories already underway within these countries rather than sanctions themselves. Substantively, this weakens the causal interpretation of the original findings and suggests the earlier significant relationship was at least partially capturing underlying country-specific corruption trends rather than a direct sanctions effect. The insignificance of the association of sanctions on corruption can be depited visually across democracy scores through Figure 4.6 below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SANCTION-V3_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 4.6</p>
<p><strong>Notes:</strong> After introducing country-specific time trends, the marginal effect of <em>sanction_intensity</em> is no longer statistically distinguishable from zero across democracy levels, as shown by the confidence interval overlapping the zero line throughout the distribution. This suggests the earlier significant relationship was at least partially driven by pre-existing country-level corruption trajectories rather than sanctions themselves.</p>
</section>
</section>
<section id="empirical-extension-2-year-lead-sanction-placebo-test" class="level2">
<h2 class="anchored" data-anchor-id="empirical-extension-2-year-lead-sanction-placebo-test">(5) Empirical Extension (2-Year Lead Sanction Placebo Test)</h2>
<p>The following table (Figure 5.1) presents the result of regressing corruption on sanction intensity two years ahead of the original imposition of U.S.-only sanction country-year:</p>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_0mb341ske2qmdis4l8nh = TinyTable.createTableFunctions("tinytable_0mb341ske2qmdis4l8nh");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '22', j: 2 } ], css_id: 'tinytable_css_v1fo8jfcct0or5ykhy22',}, 
          { positions: [ { i: '12', j: 2 } ], css_id: 'tinytable_css_i19k8uw4etwrzdone1o4',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '18', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '21', j: 2 } ], css_id: 'tinytable_css_ir7oqej09uub7hue6puq',}, 
          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_sl1841x5w3kfdxa6d8hd',}, 
          { positions: [ { i: '22', j: 1 } ], css_id: 'tinytable_css_ms319dk2ax1bpa2uumux',}, 
          { positions: [ { i: '12', j: 1 } ], css_id: 'tinytable_css_c52ot9sc6r5n8j3l8qe2',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '18', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 }, { i: '21', j: 1 } ], css_id: 'tinytable_css_7oypyoincudaxj6vroa6',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_x7kiewztmxzj121r45q8',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_0mb341ske2qmdis4l8nh.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_0mb341ske2qmdis4l8nh td.tinytable_css_v1fo8jfcct0or5ykhy22, #tinytable_0mb341ske2qmdis4l8nh th.tinytable_css_v1fo8jfcct0or5ykhy22 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_0mb341ske2qmdis4l8nh td.tinytable_css_i19k8uw4etwrzdone1o4, #tinytable_0mb341ske2qmdis4l8nh th.tinytable_css_i19k8uw4etwrzdone1o4 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_0mb341ske2qmdis4l8nh td.tinytable_css_ir7oqej09uub7hue6puq, #tinytable_0mb341ske2qmdis4l8nh th.tinytable_css_ir7oqej09uub7hue6puq { text-align: center }
    #tinytable_0mb341ske2qmdis4l8nh td.tinytable_css_sl1841x5w3kfdxa6d8hd, #tinytable_0mb341ske2qmdis4l8nh th.tinytable_css_sl1841x5w3kfdxa6d8hd {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_0mb341ske2qmdis4l8nh td.tinytable_css_ms319dk2ax1bpa2uumux, #tinytable_0mb341ske2qmdis4l8nh th.tinytable_css_ms319dk2ax1bpa2uumux {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.1em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_0mb341ske2qmdis4l8nh td.tinytable_css_c52ot9sc6r5n8j3l8qe2, #tinytable_0mb341ske2qmdis4l8nh th.tinytable_css_c52ot9sc6r5n8j3l8qe2 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_0mb341ske2qmdis4l8nh td.tinytable_css_7oypyoincudaxj6vroa6, #tinytable_0mb341ske2qmdis4l8nh th.tinytable_css_7oypyoincudaxj6vroa6 { text-align: left }
    #tinytable_0mb341ske2qmdis4l8nh td.tinytable_css_x7kiewztmxzj121r45q8, #tinytable_0mb341ske2qmdis4l8nh th.tinytable_css_x7kiewztmxzj121r45q8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_0mb341ske2qmdis4l8nh" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="2">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">sanction_intensity_lead2</td>
                  <td data-row="1" data-col="2">-0.00021*</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.00010)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">democracy_score</td>
                  <td data-row="3" data-col="2">-0.01863**</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.00566)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">gdp_growth</td>
                  <td data-row="5" data-col="2">0.00003</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.00056)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">log_gdppc</td>
                  <td data-row="7" data-col="2">0.15036***</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.04419)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">pol_stability</td>
                  <td data-row="9" data-col="2">-0.00805</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.00772)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">sanction_intensity_lead2 × democracy_score</td>
                  <td data-row="11" data-col="2">0.00002+</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2">(0.00001)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">Num.Obs.</td>
                  <td data-row="13" data-col="2">448</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1">R2</td>
                  <td data-row="14" data-col="2">0.986</td>
                </tr>
                <tr>
                  <td data-row="15" data-col="1">R2 Adj.</td>
                  <td data-row="15" data-col="2">0.985</td>
                </tr>
                <tr>
                  <td data-row="16" data-col="1">R2 Within</td>
                  <td data-row="16" data-col="2">0.075</td>
                </tr>
                <tr>
                  <td data-row="17" data-col="1">R2 Within Adj.</td>
                  <td data-row="17" data-col="2">0.061</td>
                </tr>
                <tr>
                  <td data-row="18" data-col="1">AIC</td>
                  <td data-row="18" data-col="2">-1703.9</td>
                </tr>
                <tr>
                  <td data-row="19" data-col="1">BIC</td>
                  <td data-row="19" data-col="2">-1494.5</td>
                </tr>
                <tr>
                  <td data-row="20" data-col="1">RMSE</td>
                  <td data-row="20" data-col="2">0.03</td>
                </tr>
                <tr>
                  <td data-row="21" data-col="1">FE: country</td>
                  <td data-row="21" data-col="2">X</td>
                </tr>
                <tr>
                  <td data-row="22" data-col="1">FE: year</td>
                  <td data-row="22" data-col="2">X</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<p>Figure 5.1</p>
<p>The placebo specification replaces current sanction intensity with a two-year lead of <em>sanction_intensity</em>, testing whether future sanctions exposure predicts present corruption outcomes. Because the average sanctions episode in the sample lasts roughly one year, using a two-year lead provides a stricter test against reverse causality. The significance of the placebo coefficient on sanction_intensity suggests that part of the baseline relationship may reflect pre-existing country trajectories or endogenous con founders rather than a purely causal sanctions. To elaborate, the coefficient on <em>sanction_intensity_lead2</em> remains negative and statistically significant at the 5 percent level (<code>β = -0.00021, p &lt; 0.05</code>), while the interaction term with <em>democracy_score</em> is positive and marginally significant. Substantively, the magnitude remains similar to the baseline model. A 100-point increase in future sanction intensity is associated with roughly a <code>0.021</code> decrease in the corruption index in lower-democracy countries. Relative to the corruption standard deviation (<code>0.297</code>), this is still around 7 percent of one standard deviation, suggesting the estimated relationship is not trivially small. And because this placebo model uses future sanctions to predict current corruption outcomes, the significance of the coefficient is problematic for a strong causal interpretation, because if sanctions were purely causing changes in corruption, future sanctions exposure should not systematically predict present corruption levels. Instead, these results suggest that countries later selected into higher sanctions intensity may already have been following distinct institutional or corruption trajectories beforehand. This aligns with the broader endogeneity concerns discussed earlier regarding sanction selection, pre-existing institutional decline, and country-specific trends. While the placebo coefficients are somewhat weaker than the baseline estimates of -0.00026, they remain statistically significant enough to suggest that omitted variable bias or pre-existing trends likely explain at least part of the original relationship. The magintiude of this signficance across democracy types is depicted in Figure 5.2 below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SANCTION-V3_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Figure 5.2</p>
<p><strong>Notes:</strong> The placebo specification continues to show a statistically significant negative relationship in lower-democracy regimes, reinforcing concerns that pre-existing political or institutional trajectories may still be driving part of the observed sanctions-corruption relationship rather than sanctions themselves.</p>
<hr>
</section>
<section id="policy-implications-and-future-research" class="level2">
<h2 class="anchored" data-anchor-id="policy-implications-and-future-research">(6) Policy Implications and Future Research</h2>
<p>The results of this project ultimately shifted my interpretation of the relationship between sanctions and corruption from where I initially began. Going into the analysis, I expected more intense sanctions exposure to increase corruption, particularly in more autocratic regimes where weakened transparency, economic scarcity, and concentrated elite control could create stronger incentives for rent-seeking behavior. While the baseline regressions initially appeared to support a statistically significant heterogeneous relationship by regime type, the estimated direction of the effect was opposite of the original hypothesis, with greater sanctions intensity associated with lower measured corruption outcomes in less democratic countries. More importantly, the placebo tests and the inclusion of country-specific time trends substantially weakened the causal interpretation of the findings through evidence for reverse causality/confounders and a loss of significance of the main regression, respectively. Once I accounted for pre-existing country-level corruption trajectories, the previously significant relationships lost statistical significance entirely.</p>
<p>As a result, I really do not believe this project examining sanction’s impact on corruption provides strong causal evidence for either supporting or rejecting the hypothesis. Rather I believe the project highlights the methodological difficulty of identifying causal sanctions effects in observational international data. Countries are not sanctioned randomly, and the same geopolitical, institutional, and economic factors that increase the likelihood of sanctions exposure may also shape corruption outcomes over time. The placebo results especially suggest that sanction selection dynamics and underlying institutional trajectories are likely driving at least part of the observed relationships.</p>
<p>From a policy perspective, these findings suggest caution in making strong claims that sanctions systematically worsen or reduce corruption without accounting for broader institutional dynamics. At the same time, the project still points toward plausible mechanisms through which sanctions could affect governance outcomes differently across regime types.</p>
<p>Future research would benefit from a panel event-study or staggered difference-in-differences framework similar to Gutmann et al <span class="citation" data-cites="gutmann2026">(<a href="#ref-gutmann2026" role="doc-biblioref">Gutmann, Neuenkirch, and Neumeier 2026</a>)</span>, but adapted around a sanctions-intensity design rather than only binary sanctions indicators. Such a framework would allow for a more rigorous examination of pre-treatment trends, treatment timing, and the dynamic institutional effects of prolonged sanctions exposure, providing a substantially stronger basis for causal inference.</p>
<section id="references" class="level3 unnumbered">


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-crozet2020" class="csl-entry" role="listitem">
Crozet, Matthieu, and Julian Hinz. 2020. <span>“Friendly Fire: The Trade Impact of the Russia Sanctions and Counter-Sanctions.”</span> <em>Economic Policy</em>.
</div>
<div id="ref-dreher2017" class="csl-entry" role="listitem">
Dreher, Axel, Martin Gassebner, and Lars-H. R. Siemers. 2017. <span>“Does Sanctions Cause Corruption?”</span> <em>Economics Letters</em>.
</div>
<div id="ref-escriba2004" class="csl-entry" role="listitem">
Escribà-Folch, Abel, and Joseph Wright. 2004. <span>“Political Institutions, Coercive Diplomacy, and the Duration of Economic Sanctions.”</span> <em>Journal of Conflict Resolution</em> 48 (2): 296–314. <a href="https://doi.org/10.1177/0022002703262858">https://doi.org/10.1177/0022002703262858</a>.
</div>
<div id="ref-felbermayr2020" class="csl-entry" role="listitem">
Felbermayr, Gabriel, Aleksandra Kirilakha, Constantinos Syropoulos, Erdal Yalcin, and Yoto Yotov. 2020. <span>“The Global Sanctions Data Base.”</span> <em>European Economic Review</em>.
</div>
<div id="ref-gutmann2026" class="csl-entry" role="listitem">
Gutmann, Jerg, Matthias Neuenkirch, and Florian Neumeier. 2026. <span>“Do Sanctions Increase Corruption?”</span> IZA Discussion Paper 17091. Institute of Labor Economics (IZA). <a href="https://www.econstor.eu/bitstream/10419/340063/1/ile-wp-2026-91.pdf">https://www.econstor.eu/bitstream/10419/340063/1/ile-wp-2026-91.pdf</a>.
</div>
<div id="ref-hufbauer2007" class="csl-entry" role="listitem">
Hufbauer, Gary Clyde, Jeffrey J. Schott, Kimberly Ann Elliott, and Barbara Oegg. 2007. <em>Economic Sanctions Reconsidered</em>. Peterson Institute for International Economics.
</div>
<div id="ref-kwon2025growth" class="csl-entry" role="listitem">
Kwon, Ohyun, Constantinos Syropoulos, and Yoto V. Yotov. 2025. <span>“Do Sanctions Affect Growth?”</span> 2025-16. Center for Global Policy Analysis, LeBow College of Business, Drexel University. <a href="https://www.lebow.drexel.edu/sites/default/files/2025-04/202516-cgpa-do-sactions-affect-growth.pdf">https://www.lebow.drexel.edu/sites/default/files/2025-04/202516-cgpa-do-sactions-affect-growth.pdf</a>.
</div>
<div id="ref-morgan2014" class="csl-entry" role="listitem">
Morgan, T. Clifton, Navin Bapat, and Yoshiharu Kobayashi. 2014. <span>“Threat and Imposition of Economic Sanctions 1945–2005.”</span> <em>Conflict Management and Peace Science</em>.
</div>
<div id="ref-neuenkirch2016" class="csl-entry" role="listitem">
Neuenkirch, Matthias, and Florian Neumeier. 2016. <span>“The Impact of US Sanctions on Poverty.”</span> <em>Journal of Development Economics</em>.
</div>
<div id="ref-pellegrini2008" class="csl-entry" role="listitem">
Pellegrini, Lorenzo, and Reyer Gerlagh. 2008. <span>“Causes of Corruption: A Survey of Cross-Country Analyses and Extended Results.”</span> <em>Economics of Governance</em> 9 (3): 245–63. <a href="https://doi.org/10.1007/s10101-007-0033-4">https://doi.org/10.1007/s10101-007-0033-4</a>.
</div>
<div id="ref-treisman2000" class="csl-entry" role="listitem">
Treisman, Daniel. 2000. <span>“The Causes of Corruption: A Cross-National Study.”</span> <em>Journal of Public Economics</em> 76 (3): 399–457. <a href="https://doi.org/10.1016/S0047-2727(99)00092-4">https://doi.org/10.1016/S0047-2727(99)00092-4</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>